# Generated by Django 5.0.3 on 2024-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=255)),
                ('chainId', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=255)),
                ('blockNumber', models.BigIntegerField()),
                ('gasPrice', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('burnedFees', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('index', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cfrom', models.CharField(max_length=255)),
                ('fto', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
